<?php
    $list_cat=[];
    foreach ($block->getCatCollection() as $key=>$post){
        $list_cat[]=
            [
                'id'=>$post->getId(),
                'parent_id'=>$post->getParentId(),
                'name'=>$post->getName()
            ];
    }

$list_tag=[];
foreach ($block->getTagCollection() as $key=>$tag){
    $list_tag[]=
        [
            'id'=>$tag->getId(),
            'name'=>$tag->getName()
        ];
}
?>
<div class="blog-sidebar">
    <div class="category">
            <h3>CATEGORY</h3>
        <div class="tree-menu">
            <?php   $block->showCategories($list_cat,0,''); ?>
        </div>
    </div>
    <div class="tag">
            <h3>TAG</h3>
        <div class="list-tag">
            <ul>
                <?php
                    foreach($list_tag as $tag){
                ?>
                <li><a href="<?php echo $this->getUrl('*/tag/',['id' => $tag['id']]);?>"><?php echo $tag['name']?></a></li>
                <?php } ?>
            </ul>
        </div>
    </div>
    <div class="search">
        <h3>SEARCH</h3>
        <div class="form">
            <form action="<?php echo $this->getUrl('*/post/search')?>" method="get">
                <div class="form-wrapper">
                    <input type="text" class="input-search" name="key">
                    <input type="submit" placeholder="Type something here" class="input-button" value="Search">
                </div>
            </form>
        </div>

    </div>
    <div class="option">
        <h3>Option</h3>
        <form action="<?php echo $this->getUrl('*/post/date')?>" method="post">
            <div class="field overview required" data-role="filter-form" id="date_range">
                 <span class="field-row">
                     <label for="date_from"><span><?php echo __('From') ?>:</span> </label>
                     <input class="input-text required-entry" type="text" id="date_from" name="from"/>
                       <span id="date_from_advice"></span>
                 </span>
                <span class="field-row"><label for="date_to"><span><?php echo __('To') ?>:</span></label>
                     <input class="input-text required-entry" type="text" id="date_to" name="report_to"/>
                    <span id="date_to_advice"></span>
                </span>
                <input type="submit" placeholder="Type something here" class="input-button" value="Show post">
            </div>
        </form>
    </div>
</div>
